name: build
on:
  push:
    branches:
      - master

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Run linters
        working-directory: .
        run: |
          chmod +x conf/run_linters.sh
          conf/run_linters.sh
      - name: Build image and push to GH registry
        uses: docker/build-push-action@v4
        with:
          context: .
          file: conf/snapshot.Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
